language: nim
rust: stable
script:
  - nimble build

before_deploy:
  - copy ./src/index.html > ./dist/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_access_token
  keep-history: true
  on:
    branch: nim-build
  local-dir: dist