os:
  - linux

install:
  - |
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
before_script:
  - export PATH=$HOME/.nimble/bin:$PATH

script:
  - nimble build

before_deploy:
  - cp ./src/index.html ./dist/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $github_access_token
  keep-history: true
  on:
    branch: nim-build
  local-dir: dist